name: Shared Link
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest ]
        java: [ '17' ]
      fail-fast: false
    name: Build on ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Execute build
        run: ./gradlew --info --stacktrace build
      - name: Execute runtime
        run: ./gradlew --info --stacktrace runtime
      - name: Execute jpackage
        run: ./gradlew --info --stacktrace jpackage
      - name: Upload dmg as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sharedLink-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
          path: build/jpackage/*.dmg
      - name: Upload pkg as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sharedLink-jdk${{ matrix.java }}-${{ matrix.os }}-pkg
          path: build/jpackage/*.pkg
      - name: Upload exe as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sharedLink-jdk${{ matrix.java }}-${{ matrix.os }}-exe
          path: build/jpackage/*.exe
      - name: Upload msi as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sharedLink-jdk${{ matrix.java }}-${{ matrix.os }}-msi
          path: build/jpackage/*.msi