name: Shared Link
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ '17' ]
      fail-fast: false
    name: Build on ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Get Project Version
        id: get_version
        run: echo "VERSION=$(./gradlew -q printVersion | tail -n 1)" >> $GITHUB_ENV

      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME

      - name: Verify Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Execute build
        run: ./gradlew --info --stacktrace build

      - name: Execute jlink
        run: ./gradlew --info --stacktrace jlink

      - name: Execute jpackage
        run: ./gradlew --info --stacktrace jpackage

      - name: Upload mac app as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-sharedLink-${{ env.VERSION }}.app
          path: build/jpackage/*.app

      - name: Upload mac dmg as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-sharedLink-${{ env.VERSION }}.dmg
          path: build/jpackage/*.dmg

      - name: Upload mac pkg as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-sharedLink-${{ env.VERSION }}.pkg
          path: build/jpackage/*.pkg

      - name: Upload windows exe as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-sharedLink-${{ env.VERSION }}.exe
          path: build/jpackage/*.exe

      - name: Upload windows msi as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-sharedLink-${{ env.VERSION }}.msi
          path: build/jpackage/*.msi

      - name: Upload deb as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-sharedLink-${{ env.VERSION }}.deb
          path: build/jpackage/*.deb

      - name: Upload rpm as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-sharedLink-${{ env.VERSION }}.rpm
          path: build/jpackage/*.rpm