# 由于action里使用MacOS版本是ARM架构的，打包出来有问题，所以mac的包由本地打包，不通过action
name: Shared Link
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ '17' ]
      fail-fast: false
    name: Build on ${{ matrix.os }}
    steps:
      - name: Print platform information
        shell: pwsh
        run: |
          Write-Output "Operating System: $env:RUNNER_OS"
          Write-Output "Platform Version:"
          switch ($env:RUNNER_OS) {
            "Linux" {
              uname -a
              lsb_release -a
              if (-not $?) {
                cat /etc/os-release
              }
            }
            "macOS" {
              uname -a
              sw_vers
            }
            "Windows" {
              systeminfo | Select-String -Pattern "OS Name", "OS Version", "System Type"
            }
            default {
              Write-Output "Unknown OS"
            }
          }

      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME

      - name: Verify Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Execute build
        run: ./gradlew --info --stacktrace build

      - name: Execute jlink
        run: ./gradlew --info --stacktrace jlink

      - name: Execute jpackage
        run: ./gradlew --info --stacktrace jpackage

      - name: Upload windows exe as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-sharedLink-latest.exe
          path: build/jpackage/*.exe
          if-no-files-found: ignore

      - name: Upload windows msi as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-sharedLink-latest.msi
          path: build/jpackage/*.msi
          if-no-files-found: ignore

      - name: Upload ubuntu deb as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-sharedLink-latest.deb
          path: build/jpackage/*.deb
          if-no-files-found: ignore

      - name: Upload ubuntu rpm as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-sharedLink-latest.rpm
          path: build/jpackage/*.rpm
          if-no-files-found: ignore