name: Shared Link
on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        java: [ '17' ]
      fail-fast: false
    name: Build on ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME

      - name: Verify Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Execute build
        run: ./gradlew --info --stacktrace build

      - name: Execute jlink
        run: ./gradlew --info --stacktrace jlink

      - name: Execute jpackage
        run: ./gradlew --info --stacktrace jpackage

      - name: Upload application as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sharedLink
          path: build/jpackage/